### ISSUE TITLE
Audio stuttering

### ISSUE THREAD

**Issue by NayNes** [the-raspberry-pi-guy/game_stream#1]
Hi,
first of all thank you for the straightforward guide! :) Everything works perfectly, the only problem is the audio, it stutters to the point that its unplayable. I've updated raspbian & moonlight and reinstalled all of it, but no change.
I am using a raspberry pi 2 with ethernet (I tested my bandwith with nethogs and iperf and everything seems to be in order, 80-100 mbps)

**Comment by the-raspberry-pi-guy** [comment]
I just updated Moonlight to the latest version - open another issue if you still have problems!
